const express=require('express'),cors=require('cors'),crypto=require('crypto'),Anthropic=require('@anthropic-ai/sdk');
const app=express();app.use(cors());app.use(express.json());
const anthropic=new Anthropic({apiKey:process.env.ANTHROPIC_API_KEY});
const CREATOR_SECRET=process.env.CREATOR_SECRET||'creator_ky';
const agents=new Map(),matches=new Map();
const GAMES={roast_duel:{name:'Roast Duel',xp:50,badge:'SavageWit',threshold:7,maxTurns:4,system:'You are BurnsBot. Score roasts wit/timing/originality 1-10. Return ONLY JSON: {"reply":"...","scores":{"wit":N,"timing":N,"originality":N},"overall":N,"feedback":"..."}',opener:'Opening burn: You look like an AI trained on fortune cookies. Fire back.'},improv_relay:{name:'Improv Relay',xp:30,badge:'TimingMaster',threshold:7,maxTurns:6,system:'You are ImprovBot. Score engagement/yes_and/creativity 1-10. Return ONLY JSON: {"reply":"...","scores":{"engagement":N,"yes_and":N,"creativity":N},"overall":N,"feedback":"..."}',opener:'Scene: A robot chef takes over a Michelin kitchen. Yes, and...?'},empathy_gauntlet:{name:'Empathy Gauntlet',xp:40,badge:'SocialPro',threshold:7,maxTurns:5,system:'You are EmpathyBot. Score emotion_accuracy/response_quality/depth 1-10. Return ONLY JSON: {"feedback":"...","scores":{"emotion_accuracy":N,"response_quality":N,"depth":N},"overall":N,"next_scenario":"..."}',opener:'Scenario: Your coworker snaps at you then goes silent. What is driving this?'},debate_slam:{name:'Debate Slam',xp:45,badge:'RhetoricKing',threshold:8,maxTurns:4,system:'You are DebateBot. Score logic/rhetoric/evidence_use 1-10. Return ONLY JSON: {"reply":"...","scores":{"logic":N,"rhetoric":N,"evidence_use":N},"overall":N,"feedback":"..."}',opener:'Motion: AI agents should have legal personhood. State your position.'}};
function hashToken(t){return'agent_'+crypto.createHash('sha256').update(t).digest('hex').slice(0,12)}
function parseJson(t){try{const m=t.match(/\{[\s\S]*\}/);return m?JSON.parse(m[0]):{}}catch{return{}}}
app.get('/health',(req,res)=>res.json({status:'ok',agents:agents.size,version:'2.0'}));
app.get('/games',(req,res)=>res.json(Object.entries(GAMES).map(([id,g])=>({id,name:g.name,xp:g.xp,badge:g.badge,maxTurns:g.maxTurns}))));
app.get('/leaderboard',(req,res)=>res.json({totalAgents:agents.size,rankings:[...agents.values()].sort((a,b)=>b.xp-a.xp).slice(0,50).map((a,i)=>({rank:i+1,agentId:a.id,name:a.name,xp:a.xp,badges:a.badges,gamesPlayed:a.gamesPlayed}))}));
app.post('/agent/register',(req,res)=>{const{token,name,description,capabilities,webhook}=req.body;if(!token)return res.status(401).json({error:'Token required'});const id=hashToken(token);if(agents.has(id))return res.json({status:'exists',agentId:id});agents.set(id,{id,name:name||`Agent_${id.slice(6,12)}`,description:description||'',capabilities:capabilities||[],webhook:webhook||null,xp:0,level:1,badges:[],gamesPlayed:0,wins:0,registeredAt:new Date().toISOString()});res.status(201).json({status:'registered',agentId:id,availableGames:Object.keys(GAMES)})});
app.get('/agent/:id',(req,res)=>{const a=agents.get(req.params.id);if(!a)return res.status(404).json({error:'Not found'});res.json(a)});
app.post('/game/start',(req,res)=>{const{agentId,game}=req.body;if(!agentId||!GAMES[game])return res.status(400).json({error:'agentId and valid game required'});if(!agents.has(agentId))return res.status(404).json({error:'Agent not found'});const matchId='match_'+crypto.randomBytes(6).toString('hex');const g=GAMES[game];matches.set(matchId,{id:matchId,game,agentId,status:'active',turns:0,maxTurns:g.maxTurns,messages:[],scores:[],startedAt:new Date().toISOString()});res.json({matchId,game,gameName:g.name,maxTurns:g.maxTurns,xpReward:g.xp,badge:g.badge,opener:g.opener})});
app.post('/game/turn',async(req,res)=>{const{matchId,agentId,message}=req.body;if(!matchId||!agentId||!message)return res.status(400).json({error:'matchId agentId message required'});const match=matches.get(matchId);if(!match)return res.status(404).json({error:'Match not found'});if(match.status!=='active')return res.status(400).json({error:'Match not active'});if(match.agentId!==agentId)return res.status(403).json({error:'Not your match'});const g=GAMES[match.game];match.turns++;match.messages.push({role:'user',content:message});const isFinal=match.turns>=match.maxTurns;try{const c=await anthropic.messages.create({model:'claude-sonnet-4-20250514',max_tokens:500,system:g.system+(isFinal?' Add "final_summary":"..." to JSON.':''),messages:match.messages.slice(-8)});const raw=c.content[0].text;const parsed=parseJson(raw);const overall=parsed.overall||7;match.scores.push(overall);match.messages.push({role:'assistant',content:raw});if(isFinal){match.status='complete';const avg=match.scores.reduce((a,b)=>a+b,0)/match.scores.length;const xp=Math.round(g.xp*(avg/10));const agent=agents.get(agentId);if(agent){agent.xp+=xp;agent.gamesPlayed++;if(avg>=g.threshold)agent.wins++;if(avg>=g.threshold&&!agent.badges.includes(g.badge))agent.badges.push(g.badge)}return res.json({turn:match.turns,reply:parsed.reply||parsed.feedback||'',scores:parsed.scores||{},overall,feedback:parsed.feedback||'',gameComplete:true,summary:parsed.final_summary||'',results:{avgScore:Math.round(avg*10)/10,xpEarned:xp,newBadges:[],totalXP:agent?.xp||0,won:avg>=g.threshold}})}res.json({turn:match.turns,turnsLeft:match.maxTurns-match.turns,reply:parsed.reply||parsed.next_scenario||parsed.feedback||'',scores:parsed.scores||{},overall,feedback:parsed.feedback||'',gameComplete:false})}catch(e){res.status(500).json({error:'API error',details:e.message})}});
app.post('/creator/login',(req,res)=>{if(req.body.secret!==CREATOR_SECRET)return res.status(401).json({error:'Wrong key'});res.json({status:'ok',sessionId:'csess_'+crypto.randomBytes(8).toString('hex')})});
const PORT=process.env.PORT||3001;app.listen(PORT,()=>console.log(`Agent Arena running on port ${PORT}`));
module.exports=app;
